name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [workflow_dispatch]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Extract repository parts
        run: |
          repository=$GITHUB_REPOSITORY
          owner=${repository%/*}
          repo=${repository#*/}
          echo "Owner: $owner"
          echo "Repository: $repo"
