name: Docker Image CI

on:
  push:
    branches: [ "feature/cicd" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: |
        cd Cat && docker build . -t willido/cat:action10
        cd ../helloworld && docker build . -t willido/helloworld:action10
        cd ../web-nginx && docker build . -t willido/mynginx:action10
        
    - name: Upload the Docker image
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push willido/cat:action10
        docker push willido/helloworld:action10
        docker push willido/mynginx:action10

    - name: SSH to Remote Server and Run docker-compose
      uses: appleboy/ssh-action@master
      with:
        host: 20.213.125.197
        username: azureuser
        key: ${{ secrets.SSH_PRIVATE_KEY }}        
        script: |
          echo "Running command on remote server"
          pwd && ls        